export const ALL_ROLES = [
  { value: "owner", label: "Owner" },
  { value: "director", label: "Director" },
  { value: "exec_manager", label: "Executive Manager" },
  { value: "sr_manager", label: "Senior Manager" },
  { value: "manager", label: "Manager" },
  { value: "community_manager", label: "Community Manager" },
  { value: "lead_developer", label: "Lead Developer" },
  { value: "developer", label: "Developer" },
  { value: "jr_developer", label: "Jr Developer" },
  { value: "bot_developer", label: "Bot Developer" },
  { value: "sr_admin", label: "Senior Admin" },
  { value: "admin", label: "Admin" },
  { value: "trial_admin", label: "Trial Admin" },
  { value: "jr_admin", label: "Jr Admin" },
  { value: "sr_mod", label: "Senior Moderator" },
  { value: "mod", label: "Moderator" },
  { value: "trial_mod", label: "Trial Moderator" },
  { value: "chat_monitor", label: "Chat Monitor" },
  { value: "sr_helper", label: "Senior Helper" },
  { value: "helper", label: "Helper" },
  { value: "trainee", label: "Trainee" },
  { value: "partner", label: "Partner" },
  { value: "content_creator", label: "Content Creator" },
  { value: "og", label: "OG" },
  { value: "champion", label: "Champion" },
  { value: "media", label: "Media" },
  { value: "elite", label: "Elite" },
  { value: "mvp", label: "MVP" },
  { value: "vip", label: "VIP" },
  { value: "booster", label: "Booster" },
  { value: "member", label: "Member" },
  { value: "default", label: "Default" },
] as const;

export type AppRole = typeof ALL_ROLES[number]["value"];

export const STAFF_ROLES: AppRole[] = [
  "owner",
  "director",
  "exec_manager",
  "sr_manager",
  "manager",
  "community_manager",
  "lead_developer",
  "developer",
  "jr_developer",
  "bot_developer",
  "sr_admin",
  "admin",
  "trial_admin",
  "jr_admin",
  "sr_mod",
  "mod",
  "trial_mod",
  "chat_monitor",
  "sr_helper",
  "helper",
  "trainee",
];

export const isStaffRole = (v: string) => STAFF_ROLES.includes(v as AppRole);

export const roleLabel = (v: string) =>
  ALL_ROLES.find((r) => r.value === v)?.label ?? v;
